USE database_name;

CREATE TABLE ITEM (
    ID INT AUTO_INCREMENT,
    CONSTRAINT ITEM_ID PRIMARY KEY (ID),
    NAME VARCHAR(50) NOT NULL,
    DATE_CREATED DATE,
    LAST_UPDATE_DATE DATE,
    DESCRIPTION VARCHAR(50)
);
